server:
  port: ${random.int[1,9999]}

spring:
  application:
    name: address-service
  cloud:
    consul:
      config:
        enabled: true
        format: YAML
      discovery:
        enabled: true
        instanceZone: zone2
        instanceId: ${spring.application.name}:${server.port}
        tags: urlprefix-/address

management:
  server:
    port: 4452